# Generated by Django 3.2.6 on 2021-10-05 21:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
                ('imagem', stdimage.models.StdImageField(upload_to='carros', verbose_name='imagem')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('telefone', models.CharField(max_length=11)),
                ('parcelas', models.IntegerField(validators=[django.core.validators.MinValueValidator(36), django.core.validators.MaxValueValidator(180)])),
                ('modelo_desejado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.carro')),
            ],
        ),
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.carro')),
                ('vencedor', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.cliente')),
            ],
        ),
    ]
